title: klimavernetzung-dresden.de
url: "https://klimavernetzung-dresden.de/"
theme: minima
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
